# Generated by Django 4.1.1 on 2022-09-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
                ('history', models.CharField(default=None, max_length=400)),
                ('trivia', models.CharField(default=None, max_length=200)),
                ('location_image', models.CharField(default=None, max_length=300)),
                ('youtube_id', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
