# Generated by Django 4.1.1 on 2022-09-08 23:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dangers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
                ('history', models.CharField(default=None, max_length=400)),
                ('trivia', models.CharField(default=None, max_length=200)),
                ('location_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=300), size=None)),
                ('youtube_id', models.CharField(default=None, max_length=100)),
                ('dangers', models.ManyToManyField(related_name='locations', to='dangers.danger')),
            ],
        ),
    ]
