# Generated by Django 4.1.1 on 2022-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangers', '0002_alter_danger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danger',
            name='name',
            field=models.CharField(blank=True, choices=[('Low Risk', 'Low Risk'), ('Medium Risk', 'Medium Risk'), ('High Risk', 'High Risk')], max_length=100),
        ),
    ]
