# Generated by Django 4.1.1 on 2022-09-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dangers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('origin', models.CharField(default=None, max_length=100)),
                ('height', models.CharField(default=None, max_length=100)),
                ('languages', models.CharField(default=None, max_length=100)),
                ('images', models.CharField(default=None, max_length=300)),
                ('strengths', models.CharField(default=None, max_length=300)),
                ('weaknesses', models.CharField(default=None, max_length=300)),
                ('about', models.CharField(default=None, max_length=100)),
                ('dangers', models.ManyToManyField(related_name='dangers', to='dangers.danger')),
            ],
        ),
    ]
