# Generated by Django 4.1.1 on 2022-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='about',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
