# Generated by Django 4.1.1 on 2022-09-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0002_alter_creature_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='weaknesses',
        ),
    ]
